/**
 * Unit tests for the SDP body generated by RaopRtspSession during ANNOUNCE.
 * Verifies format, line order, and L16 fmtp attribute values.
 */

import { describe, expect, it } from "bun:test";
import { buildSdp } from "@/protocols/raop/RaopRtspSession.ts";

describe("buildSdp", () => {
  const SDP = buildSdp(
    12345678, // sessionId
    "192.168.1.2", // localIp
    "192.168.1.100", // remoteIp
    44100, // sampleRate
    2, // channels
    2 // bytesPerChannel (16-bit)
  );

  it("starts with v=0", () => {
    expect(SDP.startsWith("v=0")).toBe(true);
  });

  it("contains the session ID in the origin line", () => {
    expect(SDP).toContain("o=iTunes 12345678 0 IN IP4 192.168.1.2");
  });

  it("contains the connection line with the remote IP", () => {
    expect(SDP).toContain("c=IN IP4 192.168.1.100");
  });

  it("specifies L16 payload type 96 at the correct sample rate and channels", () => {
    expect(SDP).toContain("a=rtpmap:96 L16/44100/2");
  });

  it("includes the Apple RAOP fmtp line with 352 frames per packet and 16-bit depth", () => {
    // Format: a=fmtp:96 <framesPerPkt> 0 <bits> 40 10 14 <ch> 255 0 0 <sr>
    expect(SDP).toContain("a=fmtp:96 352 0 16 40 10 14 2 255 0 0 44100");
  });

  it("uses RTP/AVP transport", () => {
    expect(SDP).toContain("m=audio 0 RTP/AVP 96");
  });

  it("ends with a trailing CRLF", () => {
    expect(SDP.endsWith("\r\n")).toBe(true);
  });

  it("uses CRLF line endings throughout", () => {
    const lines = SDP.split("\r\n").filter((l) => l.length > 0);
    expect(lines.length).toBeGreaterThanOrEqual(7);
  });

  it("adapts bits-per-channel for 24-bit audio", () => {
    const sdp24 = buildSdp(1, "10.0.0.1", "10.0.0.2", 48000, 2, 3);
    expect(sdp24).toContain("a=rtpmap:96 L16/48000/2");
    expect(sdp24).toContain("a=fmtp:96 352 0 24 40 10 14 2 255 0 0 48000");
  });
});
