// ============================================================================
// Companion Protocol Specific Types
// ============================================================================

import { EventEmitter } from "eventemitter3";

import { createLogger } from "@/logging/logging";
import type { ClientDeviceInfo } from "@/core/client-identity.ts";
import type { HAPCredentials } from "@/protocols/companion/layers/HAPAuthenticationService.ts";
import type {
  CompanionCommand,
  CompanionOpackMessage,
  TrackableCompanionOpackMessage,
} from "@/protocols/companion/messages/CompanionOpackMessage.ts";
import { createSessionStopCommand } from "@/protocols/companion/messages/sessionStop.ts";
import { createSessionStartCommand } from "@/protocols/companion/messages/sessionStart.ts";
import type {
  CommandOutputOf,
  CommandResponseOf,
} from "@/protocols/types/BaseProtocol.ts";
import { HapFramedChannel } from "@/protocols/companion/layers/HapFramedChannel.ts";

const logger = createLogger("bunatv:companion:session");

export interface CompanionSessionEvents {
  "state-changed": (state: SessionState, previous: SessionState) => void;
  "session-established": (info: CompanionSessionInfo) => void;
  "session-ended": () => void;
  message: (message: CompanionOpackMessage) => void;
}

export class SessionError extends Error {
  constructor(
    message: string,
    public readonly code?: string,
    public override readonly cause?: Error
  ) {
    super(message);
    this.name = "SessionError";
  }
}

export enum SessionState {
  /** No session established */
  Inactive = "inactive",
  /** Session start request sent */
  Starting = "starting",
  /** Session established and active */
  Active = "active",
  /** Session stop request sent */
  Stopping = "stopping",
  /** Session ended */
  Stopped = "stopped",
  /** Session error occurred */
  Error = "error",
}

/**
 * Options required to start a Companion protocol session
 */
export interface CompanionSessionStartOptions {
  /** Client device identity (BunATV's identity) */
  clientDeviceInfo: ClientDeviceInfo;
  /** HAP pairing credentials (contains clientId for _idsID field) */
  credentials?: HAPCredentials;
}

/**
 * Service types for Companion protocol session endpoints
 */
export enum ServiceType {
  /** TV Remote Services - primary endpoint */
  TVRemoteServices = "com.apple.tvremoteservices",
  /** Media Control */
  MediaControl = "com.apple.mediacontrol",
  /** System Services */
  SystemServices = "com.apple.system",
}

/**
 * Session information for Companion protocol
 */
export interface CompanionSessionInfo {
  /** Local session ID (generated by client) */
  localSessionId: number;
  /** Remote session ID (provided by Apple TV) */
  remoteSessionId: number;
  /** Combined 64-bit session ID */
  combinedSessionId: bigint;
  /** Service type */
  serviceType: ServiceType;
  /** Session start timestamp */
  startTime: Date;
  /** Last activity timestamp */
  lastActivity: Date;
}

export interface SessionConfig {
  serviceType?: ServiceType;
  timeout?: number;
  autoRetry?: boolean;
  maxRetries?: number;
}

export class CompanionSessionService extends EventEmitter<CompanionSessionEvents> {
  private _state: SessionState = SessionState.Inactive;
  private _sessionInfo?: CompanionSessionInfo;
  private config: Required<SessionConfig>;

  private transactionId = 1;
  private pendingRequests = new Map<
    number,
    {
      resolve: (response: TrackableCompanionOpackMessage) => void;
      reject: (error: Error) => void;
      timeout: NodeJS.Timeout;
    }
  >();
  private retryCount = 0;
  private establishmentPromise?: Promise<CompanionSessionInfo>;
  private sessionStartOptions?: CompanionSessionStartOptions;

  constructor(
    private readonly hapFrameChannel: HapFramedChannel,
    config?: SessionConfig
  ) {
    super();

    this.config = {
      serviceType: ServiceType.TVRemoteServices,
      timeout: 10000,
      autoRetry: true,
      maxRetries: 3,
      ...config,
    };
    this.hapFrameChannel.on("message", (message) => {
      this.handleMessage(message);
    });

    logger.info(
      { serviceType: this.config.serviceType, timeout: this.config.timeout },
      "CompanionSessionService initialized"
    );
  }

  get state(): SessionState {
    return this._state;
  }

  get isActive(): boolean {
    return (
      this._state === SessionState.Active && this._sessionInfo !== undefined
    );
  }

  async start(
    options: CompanionSessionStartOptions
  ): Promise<CompanionSessionInfo> {
    logger.info(
      { serviceType: this.config.serviceType },
      "Starting Companion session"
    );

    this.sessionStartOptions = options;

    if (!this.hapFrameChannel.isReady()) {
      logger.error("Channel not ready");
      throw new SessionError("Channel not ready", "TRANSPORT_NOT_READY");
    }

    if (!this.hapFrameChannel.isEncrypted()) {
      logger.error("Encryption not enabled - session requires encryption");
      throw new SessionError(
        "Encryption not enabled - session requires encryption",
        "ENCRYPTION_REQUIRED"
      );
    }

    if (this._state === SessionState.Active && this._sessionInfo) {
      logger.debug(
        { sessionId: this._sessionInfo.combinedSessionId },
        "Returning existing active session"
      );
      return this._sessionInfo;
    }

    if (this._state === SessionState.Starting && this.establishmentPromise) {
      logger.debug("Session already starting, returning existing promise");
      return this.establishmentPromise;
    }

    logger.debug("Initiating new session establishment");
    this.establishmentPromise = this.performSessionStart();
    return this.establishmentPromise;
  }

  async stop(): Promise<void> {
    logger.info({ state: this._state }, "Stopping Companion session");
    if (
      this._state === SessionState.Inactive ||
      this._state === SessionState.Stopped
    ) {
      logger.debug("Session already inactive/stopped");
      return;
    }

    if (!this._sessionInfo) {
      logger.debug("No session info available, marking as stopped");
      this.setState(SessionState.Stopped);
      return;
    }

    this.setState(SessionState.Stopping);

    try {
      const stopSessionCommand = createSessionStopCommand(
        this.config.serviceType,
        this._sessionInfo.combinedSessionId
      );

      await this.sendCommand(stopSessionCommand);

      logger.info("Session stopped successfully");
    } catch (error) {
      // Session stop can fail if the device already terminated the session
      // (e.g., when navigating to Home Screen). This is expected behavior.
      // Following pyatv's pattern: log as debug and continue with cleanup.
      logger.debug(
        { error },
        "Session stop failed (session may have already been terminated by device)"
      );
    } finally {
      // Always cleanup and mark as stopped, even if _sessionStop failed
      this.cleanup();
      this.setState(SessionState.Stopped);
      this.emit("session-ended");
    }
  }

  async sendCommandRaw<C extends CompanionCommand>(
    command: C
  ): Promise<CommandResponseOf<C>> {
    if (!this.isActive) {
      logger.warn(
        { state: this._state, hasSessionInfo: !!this._sessionInfo },
        "Session not active for command"
      );
    }

    const req = command.build();
    if (!req._x) {
      req._x = this.getNextTransactionId();
    }
    logger.debug(
      { commandId: req._i, transactionId: req._x },
      "Sending command through session"
    );

    logger.trace({ command: req }, "Sending command");
    const res = await this.sendRequestAndWaitForResponse(
      req as TrackableCompanionOpackMessage
    );

    logger.trace(
      { commandId: req._i, responseTransactionId: res._x },
      "Command completed successfully"
    );
    return res as CommandResponseOf<C>;
  }

  async sendCommand<const C extends CompanionCommand>(
    command: C
  ): Promise<CommandOutputOf<C>> {
    const response = await this.sendCommandRaw(command);
    return command.parse(response) as CommandOutputOf<C>;
  }

  private async performSessionStart(): Promise<CompanionSessionInfo> {
    if (!this.sessionStartOptions) {
      throw new SessionError(
        "Session start options not provided",
        "MISSING_START_OPTIONS"
      );
    }

    const localSessionId = Math.floor(Math.random() * 0xffffffff);

    this.setState(SessionState.Starting);

    try {
      const command = createSessionStartCommand(
        this.config.serviceType,
        localSessionId
      );

      const sessionId = await this.sendCommand(command);

      return this.createSessionInfo(localSessionId, Number(sessionId));
    } catch (error) {
      // Retry logic
      if (this.config.autoRetry && this.retryCount < this.config.maxRetries) {
        this.retryCount++;
        const delay = Math.min(1000 * Math.pow(2, this.retryCount - 1), 5000);
        logger.warn(
          { error, attempt: this.retryCount, delay },
          "Session establishment failed, retrying"
        );
        await new Promise((resolve) => setTimeout(resolve, delay));
        return this.performSessionStart();
      }

      logger.error(
        { error, retryCount: this.retryCount },
        "Session establishment failed after retries"
      );
      this.setState(SessionState.Error);
      throw new SessionError(
        "Session establishment failed",
        "ESTABLISHMENT_FAILED",
        error as Error
      );
    }
  }

  private async sendRequestAndWaitForResponse(
    message: TrackableCompanionOpackMessage
  ): Promise<CompanionOpackMessage> {
    return new Promise((resolve, reject) => {
      const transactionId = message._x;
      logger.trace(
        { transactionId, messageId: message._i, timeout: this.config.timeout },
        "Setting up request-response correlation"
      );

      // Set up timeout
      const timeout = setTimeout(() => {
        logger.warn(
          {
            transactionId,
            messageId: message._i,
            timeout: this.config.timeout,
          },
          "Request timeout"
        );
        this.pendingRequests.delete(transactionId);
        reject(new SessionError("Request timeout", "TIMEOUT"));
      }, this.config.timeout);

      // Store pending request
      this.pendingRequests.set(transactionId, { resolve, reject, timeout });

      const sendPromise = this.sendMessage(message);

      sendPromise.catch((error) => {
        logger.error(
          { error, transactionId, messageId: message._i },
          "Failed to send message"
        );
        clearTimeout(timeout);
        this.pendingRequests.delete(transactionId);
        reject(error);
      });
    });
  }

  async sendMessage(message: CompanionOpackMessage): Promise<void> {
    ``;
    if (!message._x) {
      message._x = this.getNextTransactionId();
    }
    logger.trace(
      { messageId: message._i, transactionId: message._x, message: message },
      "Encrypted message sent successfully"
    );
    await this.hapFrameChannel.sendMessage(message);
  }

  private handleMessage(message: CompanionOpackMessage): void {
    logger.trace(
      {
        messageId: message._i,
        transactionId: message._x,
        messageType: message._t,
      },
      "Handling incoming message"
    );
    if (message._x !== undefined) {
      // Check for pending request
      const pending = this.pendingRequests.get(message._x);
      if (pending) {
        logger.trace(
          { transactionId: message._x },
          "Found pending request for message"
        );
        clearTimeout(pending.timeout);
        this.pendingRequests.delete(message._x);

        // Check for error
        if (message._em || message._ec) {
          logger.warn(
            {
              error: message._em,
              errorCode: message._ec,
              transactionId: message._x,
            },
            "Request failed with error"
          );
          pending.reject(
            new SessionError(
              message._em || "Request failed",
              `ERROR_${message._ec}`
            )
          );
        } else {
          logger.trace(
            { transactionId: message._x },
            "Request completed successfully"
          );
          pending.resolve(message as TrackableCompanionOpackMessage);
        }
        return;
      }
    }

    // Emit as general message
    logger.trace({ messageId: message._i }, "Emitting unsolicited message");
    this.emit("message", message);
  }

  private createSessionInfo(
    localSessionId: number,
    remoteSessionId: number
  ): CompanionSessionInfo {
    const combinedSessionId =
      (BigInt(remoteSessionId) << BigInt(32)) | BigInt(localSessionId >>> 0);
    logger.info(
      {
        localSessionId,
        remoteSessionId,
        combinedSessionId: combinedSessionId.toString(),
      },
      "Creating session info"
    );
    const sessionInfo: CompanionSessionInfo = {
      localSessionId,
      remoteSessionId,
      combinedSessionId,
      serviceType: this.config.serviceType,
      startTime: new Date(),
      lastActivity: new Date(),
    };

    this._sessionInfo = sessionInfo;
    this.setState(SessionState.Active);
    logger.info(
      {
        sessionId: combinedSessionId.toString(),
        serviceType: this.config.serviceType,
      },
      "Session established successfully"
    );
    this.emit("session-established", sessionInfo);

    return sessionInfo;
  }

  private setState(newState: SessionState): void {
    const previous = this._state;
    this._state = newState;

    if (newState !== previous) {
      logger.debug(
        { previousState: previous, newState },
        "Session state changed"
      );
      this.emit("state-changed", newState, previous);
    }
  }

  private getNextTransactionId(): number {
    return this.transactionId++;
  }

  private cleanup(): void {
    logger.debug(
      { pendingRequestCount: this.pendingRequests.size },
      "Cleaning up session state"
    );
    for (const [id, pending] of this.pendingRequests) {
      clearTimeout(pending.timeout);
      pending.reject(new SessionError("Session terminated", "TERMINATED"));
    }
    this.pendingRequests.clear();

    this._sessionInfo = undefined;
    this.establishmentPromise = undefined;
    this.retryCount = 0;
    logger.trace("Session cleanup completed");
  }
}
